<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Generated by `php artisan doctrine:diff`.
 *
 * Do not edit by hand — the source of truth is the entity mapping.
 * Change it there and generate a new migration.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(60) NOT NULL, slug VARCHAR(80) NOT NULL)
            SQL);
        DB::statement(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_6FBC9426989D9B62 ON tags (slug)
            SQL);
        DB::statement(<<<'SQL'
            CREATE TABLE tasks (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(200) NOT NULL, notes CLOB DEFAULT NULL, status VARCHAR(20) NOT NULL, priority SMALLINT NOT NULL, due_on DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, position INTEGER NOT NULL, created_at DATETIME NOT NULL, list_id INTEGER NOT NULL, CONSTRAINT FK_505865973DAE168B FOREIGN KEY (list_id) REFERENCES todo_lists (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)
            SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX IDX_505865973DAE168B ON tasks (list_id)
            SQL);
        DB::statement(<<<'SQL'
            CREATE TABLE task_tag (task_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY (task_id, tag_id), CONSTRAINT FK_6C0B4F048DB60186 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_6C0B4F04BAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)
            SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX IDX_6C0B4F048DB60186 ON task_tag (task_id)
            SQL);
        DB::statement(<<<'SQL'
            CREATE INDEX IDX_6C0B4F04BAD26311 ON task_tag (tag_id)
            SQL);
        DB::statement(<<<'SQL'
            CREATE TABLE todo_lists (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, archived_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL)
            SQL);
        DB::statement(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_85714336989D9B62 ON todo_lists (slug)
            SQL);
    }

    public function down(): void
    {
        // A Doctrine diff is one-way. Going back means reverting the
        // entity change and generating a fresh diff.
    }
};
